version: "3.3"

services:
  app:
    container_name: singleton_app
    build:
      context: ..
      dockerfile: ./singleton/Dockerfile
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:postgres@psql:5432/postgres

  psql:
    image: postgres:13
    container_name: singleton_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
